// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/ocr.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OCRService service

func NewOCRServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OCRService service

type OCRService interface {
	RecognizeCaptcha(ctx context.Context, in *RecognizeCaptchaRequest, opts ...client.CallOption) (*RecognizeCaptchaResponse, error)
}

type oCRService struct {
	c    client.Client
	name string
}

func NewOCRService(name string, c client.Client) OCRService {
	return &oCRService{
		c:    c,
		name: name,
	}
}

func (c *oCRService) RecognizeCaptcha(ctx context.Context, in *RecognizeCaptchaRequest, opts ...client.CallOption) (*RecognizeCaptchaResponse, error) {
	req := c.c.NewRequest(c.name, "OCRService.RecognizeCaptcha", in)
	out := new(RecognizeCaptchaResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OCRService service

type OCRServiceHandler interface {
	RecognizeCaptcha(context.Context, *RecognizeCaptchaRequest, *RecognizeCaptchaResponse) error
}

func RegisterOCRServiceHandler(s server.Server, hdlr OCRServiceHandler, opts ...server.HandlerOption) error {
	type oCRService interface {
		RecognizeCaptcha(ctx context.Context, in *RecognizeCaptchaRequest, out *RecognizeCaptchaResponse) error
	}
	type OCRService struct {
		oCRService
	}
	h := &oCRServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OCRService{h}, opts...))
}

type oCRServiceHandler struct {
	OCRServiceHandler
}

func (h *oCRServiceHandler) RecognizeCaptcha(ctx context.Context, in *RecognizeCaptchaRequest, out *RecognizeCaptchaResponse) error {
	return h.OCRServiceHandler.RecognizeCaptcha(ctx, in, out)
}
