// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: proto/ocr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecognizeCaptchaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageBase64 string `protobuf:"bytes,1,opt,name=image_base64,json=imageBase64,proto3" json:"image_base64,omitempty"`
}

func (x *RecognizeCaptchaRequest) Reset() {
	*x = RecognizeCaptchaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ocr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeCaptchaRequest) ProtoMessage() {}

func (x *RecognizeCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeCaptchaRequest.ProtoReflect.Descriptor instead.
func (*RecognizeCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeCaptchaRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

type RecognizeCaptchaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *RecognizeCaptchaResponse) Reset() {
	*x = RecognizeCaptchaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ocr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeCaptchaResponse) ProtoMessage() {}

func (x *RecognizeCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeCaptchaResponse.ProtoReflect.Descriptor instead.
func (*RecognizeCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *RecognizeCaptchaResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_ocr_proto protoreflect.FileDescriptor

var file_proto_ocr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x63, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6f, 0x63, 0x72, 0x22, 0x3c, 0x0a, 0x17, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e,
	0x69, 0x7a, 0x65, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36,
	0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x36, 0x34, 0x22, 0x2e, 0x0a, 0x18, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a,
	0x65, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x32, 0x5f, 0x0a, 0x0a, 0x4f, 0x43, 0x52, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x43,
	0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x1c, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x67,
	0x6e, 0x69, 0x7a, 0x65, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ocr_proto_rawDescOnce sync.Once
	file_proto_ocr_proto_rawDescData = file_proto_ocr_proto_rawDesc
)

func file_proto_ocr_proto_rawDescGZIP() []byte {
	file_proto_ocr_proto_rawDescOnce.Do(func() {
		file_proto_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ocr_proto_rawDescData)
	})
	return file_proto_ocr_proto_rawDescData
}

var file_proto_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ocr_proto_goTypes = []any{
	(*RecognizeCaptchaRequest)(nil),  // 0: ocr.RecognizeCaptchaRequest
	(*RecognizeCaptchaResponse)(nil), // 1: ocr.RecognizeCaptchaResponse
}
var file_proto_ocr_proto_depIdxs = []int32{
	0, // 0: ocr.OCRService.RecognizeCaptcha:input_type -> ocr.RecognizeCaptchaRequest
	1, // 1: ocr.OCRService.RecognizeCaptcha:output_type -> ocr.RecognizeCaptchaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ocr_proto_init() }
func file_proto_ocr_proto_init() {
	if File_proto_ocr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ocr_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RecognizeCaptchaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ocr_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RecognizeCaptchaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ocr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ocr_proto_goTypes,
		DependencyIndexes: file_proto_ocr_proto_depIdxs,
		MessageInfos:      file_proto_ocr_proto_msgTypes,
	}.Build()
	File_proto_ocr_proto = out.File
	file_proto_ocr_proto_rawDesc = nil
	file_proto_ocr_proto_goTypes = nil
	file_proto_ocr_proto_depIdxs = nil
}
