// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/agent.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AgentService service

type AgentService interface {
	AddKnowledge(ctx context.Context, in *AddKnowledgeRequest, opts ...client.CallOption) (*Response, error)
	GiveAnswer(ctx context.Context, in *GiveAnswerRequest, opts ...client.CallOption) (*Response, error)
}

type agentService struct {
	c    client.Client
	name string
}

func NewAgentService(name string, c client.Client) AgentService {
	return &agentService{
		c:    c,
		name: name,
	}
}

func (c *agentService) AddKnowledge(ctx context.Context, in *AddKnowledgeRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AgentService.AddKnowledge", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentService) GiveAnswer(ctx context.Context, in *GiveAnswerRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AgentService.GiveAnswer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentService service

type AgentServiceHandler interface {
	AddKnowledge(context.Context, *AddKnowledgeRequest, *Response) error
	GiveAnswer(context.Context, *GiveAnswerRequest, *Response) error
}

func RegisterAgentServiceHandler(s server.Server, hdlr AgentServiceHandler, opts ...server.HandlerOption) error {
	type agentService interface {
		AddKnowledge(ctx context.Context, in *AddKnowledgeRequest, out *Response) error
		GiveAnswer(ctx context.Context, in *GiveAnswerRequest, out *Response) error
	}
	type AgentService struct {
		agentService
	}
	h := &agentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AgentService{h}, opts...))
}

type agentServiceHandler struct {
	AgentServiceHandler
}

func (h *agentServiceHandler) AddKnowledge(ctx context.Context, in *AddKnowledgeRequest, out *Response) error {
	return h.AgentServiceHandler.AddKnowledge(ctx, in, out)
}

func (h *agentServiceHandler) GiveAnswer(ctx context.Context, in *GiveAnswerRequest, out *Response) error {
	return h.AgentServiceHandler.GiveAnswer(ctx, in, out)
}
