// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	PostId        uint32                 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	SplitType     string                 `protobuf:"bytes,3,opt,name=split_type,json=splitType,proto3" json:"split_type,omitempty"`
	SplitSize     uint32                 `protobuf:"varint,4,opt,name=split_size,json=splitSize,proto3" json:"split_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKnowledgeRequest) Reset() {
	*x = AddKnowledgeRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKnowledgeRequest) ProtoMessage() {}

func (x *AddKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*AddKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AddKnowledgeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddKnowledgeRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddKnowledgeRequest) GetSplitType() string {
	if x != nil {
		return x.SplitType
	}
	return ""
}

func (x *AddKnowledgeRequest) GetSplitSize() uint32 {
	if x != nil {
		return x.SplitSize
	}
	return 0
}

type GiveAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint32                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ExtraContent  string                 `protobuf:"bytes,2,opt,name=extra_content,json=extraContent,proto3" json:"extra_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveAnswerRequest) Reset() {
	*x = GiveAnswerRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveAnswerRequest) ProtoMessage() {}

func (x *GiveAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveAnswerRequest.ProtoReflect.Descriptor instead.
func (*GiveAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GiveAnswerRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GiveAnswerRequest) GetExtraContent() string {
	if x != nil {
		return x.ExtraContent
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"\x86\x01\n" +
	"\x13AddKnowledgeRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\rR\x06postId\x12\x1d\n" +
	"\n" +
	"split_type\x18\x03 \x01(\tR\tsplitType\x12\x1d\n" +
	"\n" +
	"split_size\x18\x04 \x01(\rR\tsplitSize\"Q\n" +
	"\x11GiveAnswerRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\rR\x06postId\x12#\n" +
	"\rextra_content\x18\x02 \x01(\tR\fextraContent\"\n" +
	"\n" +
	"\bResponse2\x88\x01\n" +
	"\fAgentService\x12=\n" +
	"\fAddKnowledge\x12\x1a.agent.AddKnowledgeRequest\x1a\x0f.agent.Response\"\x00\x129\n" +
	"\n" +
	"GiveAnswer\x12\x18.agent.GiveAnswerRequest\x1a\x0f.agent.Response\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_agent_proto_goTypes = []any{
	(*AddKnowledgeRequest)(nil), // 0: agent.AddKnowledgeRequest
	(*GiveAnswerRequest)(nil),   // 1: agent.GiveAnswerRequest
	(*Response)(nil),            // 2: agent.Response
}
var file_proto_agent_proto_depIdxs = []int32{
	0, // 0: agent.AgentService.AddKnowledge:input_type -> agent.AddKnowledgeRequest
	1, // 1: agent.AgentService.GiveAnswer:input_type -> agent.GiveAnswerRequest
	2, // 2: agent.AgentService.AddKnowledge:output_type -> agent.Response
	2, // 3: agent.AgentService.GiveAnswer:output_type -> agent.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
