// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/post.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PostService service

func NewPostServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PostService service

type PostService interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*Response, error)
	GetPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Post, error)
	ListMainPost(ctx context.Context, in *ListMainPostRequest, opts ...client.CallOption) (*ListPostResponse, error)
	ListUserCreatedPost(ctx context.Context, in *Request, opts ...client.CallOption) (*ListPostResponse, error)
	UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, opts ...client.CallOption) (*Response, error)
	GetComment(ctx context.Context, in *Request, opts ...client.CallOption) (*CommentInfo, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*CreateResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...client.CallOption) (*Response, error)
	CreateOrRemoveLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error)
	ListLikeByUserId(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*ListLikeResponse, error)
	ListPopularTags(ctx context.Context, in *NullRequest, opts ...client.CallOption) (*Tags, error)
	CreateCollection(ctx context.Context, in *Request, opts ...client.CallOption) (*CreateResponse, error)
	DeleteCollection(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	ListCollections(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*ListCollectionsResponse, error)
}

type postService struct {
	c    client.Client
	name string
}

func NewPostService(name string, c client.Client) PostService {
	return &postService{
		c:    c,
		name: name,
	}
}

func (c *postService) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.CreatePost", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Post, error) {
	req := c.c.NewRequest(c.name, "PostService.GetPost", in)
	out := new(Post)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListMainPost(ctx context.Context, in *ListMainPostRequest, opts ...client.CallOption) (*ListPostResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListMainPost", in)
	out := new(ListPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListUserCreatedPost(ctx context.Context, in *Request, opts ...client.CallOption) (*ListPostResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListUserCreatedPost", in)
	out := new(ListPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.UpdatePostInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetComment(ctx context.Context, in *Request, opts ...client.CallOption) (*CommentInfo, error) {
	req := c.c.NewRequest(c.name, "PostService.GetComment", in)
	out := new(CommentInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateComment", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.DeleteItem", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateOrRemoveLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateOrRemoveLike", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListLikeByUserId(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*ListLikeResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListLikeByUserId", in)
	out := new(ListLikeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListPopularTags(ctx context.Context, in *NullRequest, opts ...client.CallOption) (*Tags, error) {
	req := c.c.NewRequest(c.name, "PostService.ListPopularTags", in)
	out := new(Tags)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateCollection(ctx context.Context, in *Request, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateCollection", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) DeleteCollection(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.DeleteCollection", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListCollections(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*ListCollectionsResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListCollections", in)
	out := new(ListCollectionsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostService service

type PostServiceHandler interface {
	CreatePost(context.Context, *CreatePostRequest, *Response) error
	GetPost(context.Context, *Request, *Post) error
	ListMainPost(context.Context, *ListMainPostRequest, *ListPostResponse) error
	ListUserCreatedPost(context.Context, *Request, *ListPostResponse) error
	UpdatePostInfo(context.Context, *UpdatePostInfoRequest, *Response) error
	GetComment(context.Context, *Request, *CommentInfo) error
	CreateComment(context.Context, *CreateCommentRequest, *CreateResponse) error
	DeleteItem(context.Context, *DeleteItemRequest, *Response) error
	CreateOrRemoveLike(context.Context, *LikeRequest, *Response) error
	ListLikeByUserId(context.Context, *UserIdRequest, *ListLikeResponse) error
	ListPopularTags(context.Context, *NullRequest, *Tags) error
	CreateCollection(context.Context, *Request, *CreateResponse) error
	DeleteCollection(context.Context, *Request, *Response) error
	ListCollections(context.Context, *UserIdRequest, *ListCollectionsResponse) error
}

func RegisterPostServiceHandler(s server.Server, hdlr PostServiceHandler, opts ...server.HandlerOption) error {
	type postService interface {
		CreatePost(ctx context.Context, in *CreatePostRequest, out *Response) error
		GetPost(ctx context.Context, in *Request, out *Post) error
		ListMainPost(ctx context.Context, in *ListMainPostRequest, out *ListPostResponse) error
		ListUserCreatedPost(ctx context.Context, in *Request, out *ListPostResponse) error
		UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, out *Response) error
		GetComment(ctx context.Context, in *Request, out *CommentInfo) error
		CreateComment(ctx context.Context, in *CreateCommentRequest, out *CreateResponse) error
		DeleteItem(ctx context.Context, in *DeleteItemRequest, out *Response) error
		CreateOrRemoveLike(ctx context.Context, in *LikeRequest, out *Response) error
		ListLikeByUserId(ctx context.Context, in *UserIdRequest, out *ListLikeResponse) error
		ListPopularTags(ctx context.Context, in *NullRequest, out *Tags) error
		CreateCollection(ctx context.Context, in *Request, out *CreateResponse) error
		DeleteCollection(ctx context.Context, in *Request, out *Response) error
		ListCollections(ctx context.Context, in *UserIdRequest, out *ListCollectionsResponse) error
	}
	type PostService struct {
		postService
	}
	h := &postServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PostService{h}, opts...))
}

type postServiceHandler struct {
	PostServiceHandler
}

func (h *postServiceHandler) CreatePost(ctx context.Context, in *CreatePostRequest, out *Response) error {
	return h.PostServiceHandler.CreatePost(ctx, in, out)
}

func (h *postServiceHandler) GetPost(ctx context.Context, in *Request, out *Post) error {
	return h.PostServiceHandler.GetPost(ctx, in, out)
}

func (h *postServiceHandler) ListMainPost(ctx context.Context, in *ListMainPostRequest, out *ListPostResponse) error {
	return h.PostServiceHandler.ListMainPost(ctx, in, out)
}

func (h *postServiceHandler) ListUserCreatedPost(ctx context.Context, in *Request, out *ListPostResponse) error {
	return h.PostServiceHandler.ListUserCreatedPost(ctx, in, out)
}

func (h *postServiceHandler) UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, out *Response) error {
	return h.PostServiceHandler.UpdatePostInfo(ctx, in, out)
}

func (h *postServiceHandler) GetComment(ctx context.Context, in *Request, out *CommentInfo) error {
	return h.PostServiceHandler.GetComment(ctx, in, out)
}

func (h *postServiceHandler) CreateComment(ctx context.Context, in *CreateCommentRequest, out *CreateResponse) error {
	return h.PostServiceHandler.CreateComment(ctx, in, out)
}

func (h *postServiceHandler) DeleteItem(ctx context.Context, in *DeleteItemRequest, out *Response) error {
	return h.PostServiceHandler.DeleteItem(ctx, in, out)
}

func (h *postServiceHandler) CreateOrRemoveLike(ctx context.Context, in *LikeRequest, out *Response) error {
	return h.PostServiceHandler.CreateOrRemoveLike(ctx, in, out)
}

func (h *postServiceHandler) ListLikeByUserId(ctx context.Context, in *UserIdRequest, out *ListLikeResponse) error {
	return h.PostServiceHandler.ListLikeByUserId(ctx, in, out)
}

func (h *postServiceHandler) ListPopularTags(ctx context.Context, in *NullRequest, out *Tags) error {
	return h.PostServiceHandler.ListPopularTags(ctx, in, out)
}

func (h *postServiceHandler) CreateCollection(ctx context.Context, in *Request, out *CreateResponse) error {
	return h.PostServiceHandler.CreateCollection(ctx, in, out)
}

func (h *postServiceHandler) DeleteCollection(ctx context.Context, in *Request, out *Response) error {
	return h.PostServiceHandler.DeleteCollection(ctx, in, out)
}

func (h *postServiceHandler) ListCollections(ctx context.Context, in *UserIdRequest, out *ListCollectionsResponse) error {
	return h.PostServiceHandler.ListCollections(ctx, in, out)
}
