// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post.proto

package post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListLikeResponse struct {
	List                 []*LikeItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListLikeResponse) Reset()         { *m = ListLikeResponse{} }
func (m *ListLikeResponse) String() string { return proto.CompactTextString(m) }
func (*ListLikeResponse) ProtoMessage()    {}
func (*ListLikeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{0}
}

func (m *ListLikeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLikeResponse.Unmarshal(m, b)
}
func (m *ListLikeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLikeResponse.Marshal(b, m, deterministic)
}
func (m *ListLikeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLikeResponse.Merge(m, src)
}
func (m *ListLikeResponse) XXX_Size() int {
	return xxx_messageInfo_ListLikeResponse.Size(m)
}
func (m *ListLikeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLikeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLikeResponse proto.InternalMessageInfo

func (m *ListLikeResponse) GetList() []*LikeItem {
	if m != nil {
		return m.List
	}
	return nil
}

type LikeItem struct {
	TargetId             uint32   `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TypeId               uint32   `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeItem) Reset()         { *m = LikeItem{} }
func (m *LikeItem) String() string { return proto.CompactTextString(m) }
func (*LikeItem) ProtoMessage()    {}
func (*LikeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{1}
}

func (m *LikeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeItem.Unmarshal(m, b)
}
func (m *LikeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeItem.Marshal(b, m, deterministic)
}
func (m *LikeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeItem.Merge(m, src)
}
func (m *LikeItem) XXX_Size() int {
	return xxx_messageInfo_LikeItem.Size(m)
}
func (m *LikeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeItem.DiscardUnknown(m)
}

var xxx_messageInfo_LikeItem proto.InternalMessageInfo

func (m *LikeItem) GetTargetId() uint32 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *LikeItem) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type LikeRequest struct {
	UserId               uint32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Item                 *LikeItem `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LikeRequest) Reset()         { *m = LikeRequest{} }
func (m *LikeRequest) String() string { return proto.CompactTextString(m) }
func (*LikeRequest) ProtoMessage()    {}
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{2}
}

func (m *LikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeRequest.Unmarshal(m, b)
}
func (m *LikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeRequest.Marshal(b, m, deterministic)
}
func (m *LikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeRequest.Merge(m, src)
}
func (m *LikeRequest) XXX_Size() int {
	return xxx_messageInfo_LikeRequest.Size(m)
}
func (m *LikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikeRequest proto.InternalMessageInfo

func (m *LikeRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LikeRequest) GetItem() *LikeItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateCommentRequest struct {
	PostId               uint32   `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TypeId               uint32   `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	FatherId             uint32   `protobuf:"varint,3,opt,name=father_id,json=fatherId,proto3" json:"father_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatorId            uint32   `protobuf:"varint,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{3}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *CreateCommentRequest) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *CreateCommentRequest) GetFatherId() uint32 {
	if m != nil {
		return m.FatherId
	}
	return 0
}

func (m *CreateCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateCommentRequest) GetCreatorId() uint32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

type CommentInfo struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId               uint32   `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	FatherId             uint32   `protobuf:"varint,4,opt,name=father_id,json=fatherId,proto3" json:"father_id,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreatorId            uint32   `protobuf:"varint,6,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName          string   `protobuf:"bytes,7,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatorAvatar        string   `protobuf:"bytes,8,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	LikeNum              uint32   `protobuf:"varint,9,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`
	IsLiked              bool     `protobuf:"varint,10,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentInfo) Reset()         { *m = CommentInfo{} }
func (m *CommentInfo) String() string { return proto.CompactTextString(m) }
func (*CommentInfo) ProtoMessage()    {}
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{4}
}

func (m *CommentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentInfo.Unmarshal(m, b)
}
func (m *CommentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentInfo.Marshal(b, m, deterministic)
}
func (m *CommentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentInfo.Merge(m, src)
}
func (m *CommentInfo) XXX_Size() int {
	return xxx_messageInfo_CommentInfo.Size(m)
}
func (m *CommentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CommentInfo proto.InternalMessageInfo

func (m *CommentInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommentInfo) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *CommentInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommentInfo) GetFatherId() uint32 {
	if m != nil {
		return m.FatherId
	}
	return 0
}

func (m *CommentInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *CommentInfo) GetCreatorId() uint32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *CommentInfo) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *CommentInfo) GetCreatorAvatar() string {
	if m != nil {
		return m.CreatorAvatar
	}
	return ""
}

func (m *CommentInfo) GetLikeNum() uint32 {
	if m != nil {
		return m.LikeNum
	}
	return 0
}

func (m *CommentInfo) GetIsLiked() bool {
	if m != nil {
		return m.IsLiked
	}
	return false
}

type Request struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{5}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserIdRequest struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIdRequest) Reset()         { *m = UserIdRequest{} }
func (m *UserIdRequest) String() string { return proto.CompactTextString(m) }
func (*UserIdRequest) ProtoMessage()    {}
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{6}
}

func (m *UserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdRequest.Unmarshal(m, b)
}
func (m *UserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdRequest.Marshal(b, m, deterministic)
}
func (m *UserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdRequest.Merge(m, src)
}
func (m *UserIdRequest) XXX_Size() int {
	return xxx_messageInfo_UserIdRequest.Size(m)
}
func (m *UserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdRequest proto.InternalMessageInfo

func (m *UserIdRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Item struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId               uint32   `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{7}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type UpdatePostInfoRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	UserId               uint32   `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId           uint32   `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostInfoRequest) Reset()         { *m = UpdatePostInfoRequest{} }
func (m *UpdatePostInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostInfoRequest) ProtoMessage()    {}
func (*UpdatePostInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{8}
}

func (m *UpdatePostInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostInfoRequest.Unmarshal(m, b)
}
func (m *UpdatePostInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostInfoRequest.Merge(m, src)
}
func (m *UpdatePostInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostInfoRequest.Size(m)
}
func (m *UpdatePostInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostInfoRequest proto.InternalMessageInfo

func (m *UpdatePostInfoRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostInfoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatePostInfoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostInfoRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdatePostInfoRequest) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *UpdatePostInfoRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreatePostRequest struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	TypeId               uint32   `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	CategoryId           uint32   `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MainPostId           uint32   `protobuf:"varint,6,opt,name=main_post_id,json=mainPostId,proto3" json:"main_post_id,omitempty"`
	Tags                 []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{9}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreatePostRequest) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *CreatePostRequest) GetMainPostId() uint32 {
	if m != nil {
		return m.MainPostId
	}
	return 0
}

func (m *CreatePostRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{10}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type ListMainPostRequest struct {
	LastId               uint32   `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	TypeId               uint32   `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	CategoryId           uint32   `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId               uint32   `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination           bool     `protobuf:"varint,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMainPostRequest) Reset()         { *m = ListMainPostRequest{} }
func (m *ListMainPostRequest) String() string { return proto.CompactTextString(m) }
func (*ListMainPostRequest) ProtoMessage()    {}
func (*ListMainPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{11}
}

func (m *ListMainPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMainPostRequest.Unmarshal(m, b)
}
func (m *ListMainPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMainPostRequest.Marshal(b, m, deterministic)
}
func (m *ListMainPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMainPostRequest.Merge(m, src)
}
func (m *ListMainPostRequest) XXX_Size() int {
	return xxx_messageInfo_ListMainPostRequest.Size(m)
}
func (m *ListMainPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMainPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMainPostRequest proto.InternalMessageInfo

func (m *ListMainPostRequest) GetLastId() uint32 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *ListMainPostRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListMainPostRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListMainPostRequest) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *ListMainPostRequest) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *ListMainPostRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListMainPostRequest) GetPagination() bool {
	if m != nil {
		return m.Pagination
	}
	return false
}

type ListSubPostRequest struct {
	LastId               uint32   `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	TypeId               uint32   `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	MainPostId           uint32   `protobuf:"varint,5,opt,name=main_post_id,json=mainPostId,proto3" json:"main_post_id,omitempty"`
	UserId               uint32   `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination           bool     `protobuf:"varint,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubPostRequest) Reset()         { *m = ListSubPostRequest{} }
func (m *ListSubPostRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubPostRequest) ProtoMessage()    {}
func (*ListSubPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{12}
}

func (m *ListSubPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubPostRequest.Unmarshal(m, b)
}
func (m *ListSubPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubPostRequest.Marshal(b, m, deterministic)
}
func (m *ListSubPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubPostRequest.Merge(m, src)
}
func (m *ListSubPostRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubPostRequest.Size(m)
}
func (m *ListSubPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubPostRequest proto.InternalMessageInfo

func (m *ListSubPostRequest) GetLastId() uint32 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *ListSubPostRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListSubPostRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListSubPostRequest) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *ListSubPostRequest) GetMainPostId() uint32 {
	if m != nil {
		return m.MainPostId
	}
	return 0
}

func (m *ListSubPostRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListSubPostRequest) GetPagination() bool {
	if m != nil {
		return m.Pagination
	}
	return false
}

type ListPostResponse struct {
	List                 []*Post  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostResponse) Reset()         { *m = ListPostResponse{} }
func (m *ListPostResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostResponse) ProtoMessage()    {}
func (*ListPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{13}
}

func (m *ListPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostResponse.Unmarshal(m, b)
}
func (m *ListPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostResponse.Marshal(b, m, deterministic)
}
func (m *ListPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostResponse.Merge(m, src)
}
func (m *ListPostResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostResponse.Size(m)
}
func (m *ListPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostResponse proto.InternalMessageInfo

func (m *ListPostResponse) GetList() []*Post {
	if m != nil {
		return m.List
	}
	return nil
}

type Post struct {
	Id                   uint32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Time                 string         `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	CategoryId           uint32         `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CreatorId            uint32         `protobuf:"varint,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName          string         `protobuf:"bytes,6,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	Content              string         `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatorAvatar        string         `protobuf:"bytes,8,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	CommentNum           uint32         `protobuf:"varint,9,opt,name=comment_num,json=commentNum,proto3" json:"comment_num,omitempty"`
	LikeNum              uint32         `protobuf:"varint,10,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`
	IsLiked              bool           `protobuf:"varint,11,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	IsFavorite           bool           `protobuf:"varint,12,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	Comments             []*CommentInfo `protobuf:"bytes,13,rep,name=comments,proto3" json:"comments,omitempty"`
	Tags                 []string       `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{14}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Post) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Post) GetCreatorId() uint32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *Post) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreatorAvatar() string {
	if m != nil {
		return m.CreatorAvatar
	}
	return ""
}

func (m *Post) GetCommentNum() uint32 {
	if m != nil {
		return m.CommentNum
	}
	return 0
}

func (m *Post) GetLikeNum() uint32 {
	if m != nil {
		return m.LikeNum
	}
	return 0
}

func (m *Post) GetIsLiked() bool {
	if m != nil {
		return m.IsLiked
	}
	return false
}

func (m *Post) GetIsFavorite() bool {
	if m != nil {
		return m.IsFavorite
	}
	return false
}

func (m *Post) GetComments() []*CommentInfo {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*ListLikeResponse)(nil), "post.ListLikeResponse")
	proto.RegisterType((*LikeItem)(nil), "post.LikeItem")
	proto.RegisterType((*LikeRequest)(nil), "post.LikeRequest")
	proto.RegisterType((*CreateCommentRequest)(nil), "post.CreateCommentRequest")
	proto.RegisterType((*CommentInfo)(nil), "post.CommentInfo")
	proto.RegisterType((*Request)(nil), "post.Request")
	proto.RegisterType((*UserIdRequest)(nil), "post.UserIdRequest")
	proto.RegisterType((*Item)(nil), "post.Item")
	proto.RegisterType((*UpdatePostInfoRequest)(nil), "post.UpdatePostInfoRequest")
	proto.RegisterType((*CreatePostRequest)(nil), "post.CreatePostRequest")
	proto.RegisterType((*Response)(nil), "post.Response")
	proto.RegisterType((*ListMainPostRequest)(nil), "post.ListMainPostRequest")
	proto.RegisterType((*ListSubPostRequest)(nil), "post.ListSubPostRequest")
	proto.RegisterType((*ListPostResponse)(nil), "post.ListPostResponse")
	proto.RegisterType((*Post)(nil), "post.Post")
}

func init() { proto.RegisterFile("proto/post.proto", fileDescriptor_5e57bba97c118b83) }

var fileDescriptor_5e57bba97c118b83 = []byte{
	// 926 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x51, 0x8f, 0x1b, 0x35,
	0x10, 0xce, 0x26, 0x7b, 0xd9, 0x64, 0x72, 0x89, 0x7a, 0x6e, 0x69, 0xb7, 0x57, 0x51, 0x82, 0x25,
	0x50, 0x84, 0x44, 0x4b, 0x0f, 0x09, 0x9e, 0x10, 0x1c, 0x87, 0xa8, 0x16, 0x95, 0xaa, 0xda, 0xd2,
	0xe7, 0xc8, 0xbd, 0x9d, 0x1c, 0x56, 0xb3, 0xbb, 0x61, 0xd7, 0x39, 0xe9, 0xfe, 0x0c, 0x3c, 0xf1,
	0xc8, 0x3f, 0x41, 0xe2, 0x17, 0x21, 0xa1, 0xb1, 0xbd, 0xbb, 0xde, 0x24, 0x77, 0x39, 0x78, 0xe0,
	0xcd, 0x33, 0x1e, 0xdb, 0xdf, 0xf8, 0x9b, 0xf9, 0x6c, 0xb8, 0xb3, 0x2a, 0x72, 0x95, 0x3f, 0x5d,
	0xe5, 0xa5, 0x7a, 0xa2, 0x87, 0xcc, 0xa7, 0x31, 0xff, 0x02, 0xee, 0xbc, 0x90, 0xa5, 0x7a, 0x21,
	0xdf, 0x61, 0x8c, 0xe5, 0x2a, 0xcf, 0x4a, 0x64, 0x1c, 0xfc, 0xa5, 0x2c, 0x55, 0xe8, 0x4d, 0x7b,
	0xb3, 0xd1, 0xc9, 0xe4, 0x89, 0x5e, 0x44, 0x11, 0x91, 0xc2, 0x34, 0xd6, 0x73, 0xfc, 0x1b, 0x18,
	0x54, 0x1e, 0xf6, 0x08, 0x86, 0x4a, 0x14, 0x17, 0xa8, 0xe6, 0x32, 0x09, 0xbd, 0xa9, 0x37, 0x1b,
	0xc7, 0x03, 0xe3, 0x88, 0x12, 0xf6, 0x00, 0x02, 0x75, 0xb5, 0x42, 0x9a, 0xea, 0xea, 0xa9, 0x3e,
	0x99, 0x51, 0xc2, 0x7f, 0x80, 0x91, 0x39, 0xf5, 0x97, 0x35, 0x96, 0x8a, 0xe2, 0xd6, 0x25, 0x16,
	0xcd, 0x16, 0x7d, 0x32, 0xa3, 0x84, 0xd0, 0x48, 0x85, 0xa9, 0x5e, 0xbd, 0x03, 0x0d, 0xcd, 0xf1,
	0x5f, 0x3d, 0xb8, 0x77, 0x56, 0xa0, 0x50, 0x78, 0x96, 0xa7, 0x29, 0x66, 0xca, 0xd9, 0x95, 0xe2,
	0x9d, 0x5d, 0xc9, 0xbc, 0x01, 0x16, 0x25, 0xb3, 0x10, 0xea, 0x67, 0x83, 0xa4, 0x67, 0x92, 0x31,
	0x8e, 0x28, 0x61, 0x21, 0x04, 0xe7, 0x79, 0xa6, 0x30, 0x53, 0xa1, 0x3f, 0xf5, 0x66, 0xc3, 0xb8,
	0x32, 0xd9, 0xfb, 0x00, 0xe7, 0x04, 0x20, 0xd7, 0xeb, 0x0e, 0xf4, 0xba, 0xa1, 0xf5, 0x44, 0x09,
	0xff, 0xa3, 0x0b, 0x23, 0x0b, 0x2d, 0xca, 0x16, 0x39, 0x9b, 0x40, 0xb7, 0x86, 0xd4, 0x95, 0x37,
	0xc0, 0x71, 0x4e, 0xec, 0xb5, 0x4f, 0x6c, 0x01, 0xf5, 0x37, 0x80, 0x7e, 0x00, 0x23, 0x7d, 0x38,
	0xce, 0x95, 0x4c, 0x51, 0xe3, 0x19, 0xc6, 0x06, 0x21, 0xfe, 0x24, 0x53, 0xdc, 0xc0, 0xdb, 0xdf,
	0xc0, 0xcb, 0x3e, 0x84, 0xc3, 0x6a, 0x3a, 0x13, 0x29, 0x86, 0x81, 0xde, 0x60, 0x64, 0x7d, 0x2f,
	0x45, 0x8a, 0xec, 0x23, 0x98, 0x54, 0x21, 0xe2, 0x52, 0x28, 0x51, 0x84, 0x03, 0x1d, 0x34, 0xb6,
	0xde, 0x53, 0xed, 0x64, 0x0f, 0x61, 0xb0, 0x94, 0xef, 0x70, 0x9e, 0xad, 0xd3, 0x70, 0xa8, 0x8f,
	0x09, 0xc8, 0x7e, 0xb9, 0x4e, 0x69, 0x4a, 0x96, 0x73, 0xb2, 0x92, 0x10, 0xa6, 0xde, 0x6c, 0x10,
	0x07, 0xb2, 0x24, 0x66, 0x13, 0x7e, 0x02, 0x41, 0x45, 0xe1, 0x8e, 0xab, 0xaa, 0x0a, 0xa5, 0xeb,
	0x16, 0x0a, 0x9f, 0xc1, 0xf8, 0x8d, 0x1e, 0xed, 0x2b, 0x29, 0xfe, 0x14, 0x7c, 0x5d, 0xb8, 0xb7,
	0x65, 0x81, 0xff, 0xee, 0xc1, 0x7b, 0x6f, 0x56, 0x89, 0x50, 0xf8, 0x8a, 0xca, 0x27, 0x5b, 0xe4,
	0xd7, 0xa1, 0x73, 0xf8, 0xea, 0xb6, 0xf9, 0xba, 0x07, 0x07, 0x4a, 0xaa, 0x25, 0x5a, 0x1e, 0x8d,
	0xe1, 0x62, 0xf4, 0x5b, 0x65, 0x4f, 0x0c, 0x0a, 0x85, 0x17, 0x79, 0x71, 0xd5, 0x54, 0x14, 0x54,
	0xae, 0x28, 0x61, 0x0c, 0x7c, 0x25, 0x2e, 0xca, 0xb0, 0x3f, 0xed, 0xcd, 0x86, 0xb1, 0x1e, 0xf3,
	0x3f, 0x3d, 0x38, 0x32, 0x7d, 0x40, 0x38, 0xf7, 0xb6, 0xd6, 0xf5, 0x60, 0x9d, 0x9b, 0xe8, 0xb5,
	0xea, 0xb1, 0xce, 0xc2, 0x77, 0xb3, 0xd8, 0x0b, 0x76, 0x0a, 0x87, 0xa9, 0x90, 0xd9, 0xbc, 0x6a,
	0x46, 0x53, 0x70, 0x40, 0xbe, 0x57, 0xa6, 0x21, 0xab, 0x74, 0x02, 0x27, 0x1d, 0x80, 0x41, 0x25,
	0x4a, 0xfc, 0x2f, 0x0f, 0xee, 0x92, 0x52, 0xfd, 0x68, 0x97, 0x38, 0xc9, 0x2d, 0x45, 0xab, 0xc3,
	0xc9, 0x8c, 0x12, 0x76, 0x1f, 0xfa, 0xf9, 0x62, 0x51, 0xa2, 0xaa, 0xb8, 0x34, 0x16, 0x65, 0xb0,
	0x94, 0xa9, 0x54, 0x36, 0x31, 0x63, 0xb8, 0x09, 0xfb, 0xad, 0x84, 0xf7, 0xa6, 0xe6, 0xdc, 0x6e,
	0xbf, 0x75, 0xbb, 0x8f, 0x01, 0x56, 0xe2, 0x42, 0x66, 0x42, 0xc9, 0x3c, 0xd3, 0x1d, 0x34, 0x88,
	0x1d, 0x0f, 0x65, 0xc4, 0x28, 0xa3, 0xd7, 0xeb, 0xb7, 0xff, 0x67, 0x42, 0x9b, 0x54, 0x1c, 0x6c,
	0x51, 0xf1, 0x9f, 0x33, 0x3a, 0x31, 0x8f, 0x89, 0xc9, 0xc6, 0x3e, 0x26, 0x8f, 0x5b, 0x8f, 0x09,
	0x18, 0xf9, 0xd6, 0x11, 0xe6, 0x21, 0xf9, 0xad, 0x07, 0x3e, 0x99, 0x5b, 0x9d, 0x54, 0x57, 0x5a,
	0xd7, 0xad, 0x34, 0x2a, 0x13, 0x52, 0x34, 0xd3, 0x44, 0x7a, 0xbc, 0x49, 0x91, 0xbf, 0x45, 0xd1,
	0xcd, 0xe2, 0xbc, 0x25, 0x76, 0xfd, 0x6d, 0xb1, 0x73, 0x3a, 0x25, 0x68, 0x77, 0xca, 0x2d, 0x65,
	0x90, 0x30, 0x1a, 0xfd, 0x77, 0x94, 0x10, 0xac, 0xcb, 0x8a, 0x61, 0xad, 0x93, 0x70, 0xbd, 0x4e,
	0x8e, 0x5a, 0x3a, 0x49, 0xdb, 0xca, 0x72, 0xbe, 0x10, 0x97, 0x79, 0x21, 0x15, 0x86, 0x87, 0x86,
	0x12, 0x59, 0x7e, 0x6f, 0x3d, 0xec, 0x53, 0x18, 0xd8, 0x43, 0xca, 0x70, 0xac, 0x29, 0x38, 0x32,
	0x14, 0x38, 0xaf, 0x51, 0x5c, 0x87, 0xd4, 0x5d, 0x38, 0x69, 0xba, 0xf0, 0xe4, 0x6f, 0x1f, 0x46,
	0xc4, 0xd0, 0x6b, 0x2c, 0x2e, 0xe5, 0x39, 0xb2, 0x2f, 0x01, 0x1a, 0x8d, 0x61, 0x0f, 0xec, 0x76,
	0x9b, 0xaa, 0x73, 0x6c, 0x5f, 0xea, 0xba, 0x81, 0x3b, 0xec, 0x0c, 0x0e, 0xdd, 0x0e, 0x66, 0x0f,
	0xab, 0xb7, 0x7c, 0xab, 0xab, 0x8f, 0xef, 0x37, 0x53, 0x6e, 0x35, 0xf1, 0x0e, 0x3b, 0xa5, 0x6f,
	0x43, 0xdd, 0x34, 0x2c, 0x6c, 0x02, 0xdb, 0x7d, 0x74, 0xc3, 0x16, 0x5f, 0xc3, 0xa4, 0x2d, 0xe6,
	0xec, 0x91, 0x89, 0xdd, 0x29, 0xf1, 0x3b, 0x12, 0xf9, 0x18, 0x82, 0xe7, 0xa8, 0x77, 0x65, 0xe3,
	0x6a, 0xd2, 0xc4, 0x3a, 0xf5, 0xcd, 0x3b, 0xec, 0x33, 0x80, 0xe7, 0xa8, 0xec, 0x4d, 0x6f, 0x86,
	0x6e, 0xf3, 0xc0, 0x3b, 0xec, 0x2b, 0x18, 0xb7, 0xfe, 0x31, 0xec, 0xd8, 0xbd, 0xde, 0xf6, 0xe7,
	0x66, 0x07, 0xb0, 0x4f, 0x00, 0xbe, 0xc3, 0x25, 0x2a, 0xf3, 0x2f, 0xb3, 0x60, 0x68, 0xbc, 0x23,
	0xf6, 0x59, 0x45, 0x23, 0x55, 0x12, 0x3b, 0x6a, 0xfe, 0x55, 0xd7, 0x6f, 0xff, 0x0c, 0x20, 0xc6,
	0x34, 0xbf, 0xfc, 0x17, 0x4b, 0x4e, 0x9b, 0xff, 0xe5, 0xb7, 0x57, 0xe6, 0x79, 0x66, 0x77, 0xed,
	0x6d, 0xbb, 0x8f, 0xb5, 0x4b, 0x97, 0xfb, 0x19, 0xe5, 0x9d, 0xb7, 0x7d, 0xfd, 0x5f, 0xfd, 0xfc,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x07, 0xf7, 0xe8, 0xc3, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostService service

type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*Response, error)
	ListMainPost(ctx context.Context, in *ListMainPostRequest, opts ...client.CallOption) (*ListPostResponse, error)
	ListSubPost(ctx context.Context, in *ListSubPostRequest, opts ...client.CallOption) (*ListPostResponse, error)
	UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, opts ...client.CallOption) (*Response, error)
	GetPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Post, error)
	GetComment(ctx context.Context, in *Request, opts ...client.CallOption) (*CommentInfo, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*Response, error)
	DeleteItem(ctx context.Context, in *Item, opts ...client.CallOption) (*Response, error)
	CreateLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error)
	RemoveLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error)
	ListLikeByUserId(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*ListLikeResponse, error)
}

type postServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPostServiceClient(serviceName string, c client.Client) PostServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "post"
	}
	return &postServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.CreatePost", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListMainPost(ctx context.Context, in *ListMainPostRequest, opts ...client.CallOption) (*ListPostResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.ListMainPost", in)
	out := new(ListPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListSubPost(ctx context.Context, in *ListSubPostRequest, opts ...client.CallOption) (*ListPostResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.ListSubPost", in)
	out := new(ListPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.UpdatePostInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Post, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.GetPost", in)
	out := new(Post)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetComment(ctx context.Context, in *Request, opts ...client.CallOption) (*CommentInfo, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.GetComment", in)
	out := new(CommentInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.CreateComment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteItem(ctx context.Context, in *Item, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.DeleteItem", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.CreateLike", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) RemoveLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.RemoveLike", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListLikeByUserId(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*ListLikeResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.ListLikeByUserId", in)
	out := new(ListLikeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostService service

type PostServiceHandler interface {
	CreatePost(context.Context, *CreatePostRequest, *Response) error
	ListMainPost(context.Context, *ListMainPostRequest, *ListPostResponse) error
	ListSubPost(context.Context, *ListSubPostRequest, *ListPostResponse) error
	UpdatePostInfo(context.Context, *UpdatePostInfoRequest, *Response) error
	GetPost(context.Context, *Request, *Post) error
	GetComment(context.Context, *Request, *CommentInfo) error
	CreateComment(context.Context, *CreateCommentRequest, *Response) error
	DeleteItem(context.Context, *Item, *Response) error
	CreateLike(context.Context, *LikeRequest, *Response) error
	RemoveLike(context.Context, *LikeRequest, *Response) error
	ListLikeByUserId(context.Context, *UserIdRequest, *ListLikeResponse) error
}

func RegisterPostServiceHandler(s server.Server, hdlr PostServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PostService{hdlr}, opts...))
}

type PostService struct {
	PostServiceHandler
}

func (h *PostService) CreatePost(ctx context.Context, in *CreatePostRequest, out *Response) error {
	return h.PostServiceHandler.CreatePost(ctx, in, out)
}

func (h *PostService) ListMainPost(ctx context.Context, in *ListMainPostRequest, out *ListPostResponse) error {
	return h.PostServiceHandler.ListMainPost(ctx, in, out)
}

func (h *PostService) ListSubPost(ctx context.Context, in *ListSubPostRequest, out *ListPostResponse) error {
	return h.PostServiceHandler.ListSubPost(ctx, in, out)
}

func (h *PostService) UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, out *Response) error {
	return h.PostServiceHandler.UpdatePostInfo(ctx, in, out)
}

func (h *PostService) GetPost(ctx context.Context, in *Request, out *Post) error {
	return h.PostServiceHandler.GetPost(ctx, in, out)
}

func (h *PostService) GetComment(ctx context.Context, in *Request, out *CommentInfo) error {
	return h.PostServiceHandler.GetComment(ctx, in, out)
}

func (h *PostService) CreateComment(ctx context.Context, in *CreateCommentRequest, out *Response) error {
	return h.PostServiceHandler.CreateComment(ctx, in, out)
}

func (h *PostService) DeleteItem(ctx context.Context, in *Item, out *Response) error {
	return h.PostServiceHandler.DeleteItem(ctx, in, out)
}

func (h *PostService) CreateLike(ctx context.Context, in *LikeRequest, out *Response) error {
	return h.PostServiceHandler.CreateLike(ctx, in, out)
}

func (h *PostService) RemoveLike(ctx context.Context, in *LikeRequest, out *Response) error {
	return h.PostServiceHandler.RemoveLike(ctx, in, out)
}

func (h *PostService) ListLikeByUserId(ctx context.Context, in *UserIdRequest, out *ListLikeResponse) error {
	return h.PostServiceHandler.ListLikeByUserId(ctx, in, out)
}
