// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/post.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PostService service

func NewPostServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PostService service

type PostService interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*CreatePostResponse, error)
	GetPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Post, error)
	ListMainPost(ctx context.Context, in *ListMainPostRequest, opts ...client.CallOption) (*ListPostResponse, error)
	ListUserCreatedPost(ctx context.Context, in *ListPostPartInfoRequest, opts ...client.CallOption) (*ListPostPartInfoResponse, error)
	UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, opts ...client.CallOption) (*Response, error)
	SetQualityPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetUnReadPostNum(ctx context.Context, in *Request, opts ...client.CallOption) (*UnReadPostNumResponse, error)
	UpdateLastReadTime(ctx context.Context, in *UpdateLastReadRequest, opts ...client.CallOption) (*Response, error)
	CreateSipScore(ctx context.Context, in *CreateSipScoreRequest, opts ...client.CallOption) (*CreateSipScoreResponse, error)
	UpdateSipScoreInfo(ctx context.Context, in *UpdateSipScoreInfoRequest, opts ...client.CallOption) (*Response, error)
	CreateSipScoreEntry(ctx context.Context, in *CreateSipScoreEntryRequest, opts ...client.CallOption) (*CreateSipScoreEntryResponse, error)
	UpdateSipScoreEntryInfo(ctx context.Context, in *UpdateSipScoreEntryInfoRequest, opts ...client.CallOption) (*Response, error)
	GetSipScore(ctx context.Context, in *Request, opts ...client.CallOption) (*SipScore, error)
	ListSipScoreEntry(ctx context.Context, in *ListSipScoreEntryRequest, opts ...client.CallOption) (*ListSipScoreEntryResponse, error)
	DeleteSipScoreEntries(ctx context.Context, in *DeleteSipScoreEntriesRequest, opts ...client.CallOption) (*Response, error)
	ListSipScore(ctx context.Context, in *ListSipScoreRequest, opts ...client.CallOption) (*ListSipScoreResponse, error)
	CreateSipScoreEntryCommentRating(ctx context.Context, in *CreateSipScoreEntryCommentRatingRequest, opts ...client.CallOption) (*Response, error)
	UpdateSipScoreEntryCommentRatingInfo(ctx context.Context, in *UpdateSipScoreEntryCommentRatingInfoRequest, opts ...client.CallOption) (*Response, error)
	DeleteSipScoreEntryCommentRating(ctx context.Context, in *DeleteSipScoreEntryCommentRatingRequest, opts ...client.CallOption) (*Response, error)
	ListSipScoreEntryCommentRating(ctx context.Context, in *ListSipScoreEntryCommentRatingInfoRequest, opts ...client.CallOption) (*ListSipScoreEntryCommentRatingInfoResponse, error)
	GetComment(ctx context.Context, in *Request, opts ...client.CallOption) (*CommentInfo, error)
	// 通用创建评论（target_type + target_id）
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*CreateCommentResponse, error)
	CreatePostComment(ctx context.Context, in *CreatePostCommentRequest, opts ...client.CallOption) (*CreatePostCommentResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...client.CallOption) (*Response, error)
	CreateOrRemoveLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error)
	ListLikeByUserId(ctx context.Context, in *ListPostPartInfoRequest, opts ...client.CallOption) (*ListPostPartInfoResponse, error)
	ListPopularTag(ctx context.Context, in *ListPopularTagRequest, opts ...client.CallOption) (*Tags, error)
	CreateOrRemoveCollection(ctx context.Context, in *ToggleTargetRequest, opts ...client.CallOption) (*CreateOrRemoveCollectionResponse, error)
	ListCollection(ctx context.Context, in *ListPostPartInfoRequest, opts ...client.CallOption) (*ListPostPartInfoResponse, error)
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...client.CallOption) (*Response, error)
	ListReport(ctx context.Context, in *ListReportRequest, opts ...client.CallOption) (*ListReportResponse, error)
	HandleReport(ctx context.Context, in *HandleReportRequest, opts ...client.CallOption) (*Response, error)
}

type postService struct {
	c    client.Client
	name string
}

func NewPostService(name string, c client.Client) PostService {
	return &postService{
		c:    c,
		name: name,
	}
}

func (c *postService) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*CreatePostResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreatePost", in)
	out := new(CreatePostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Post, error) {
	req := c.c.NewRequest(c.name, "PostService.GetPost", in)
	out := new(Post)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListMainPost(ctx context.Context, in *ListMainPostRequest, opts ...client.CallOption) (*ListPostResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListMainPost", in)
	out := new(ListPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListUserCreatedPost(ctx context.Context, in *ListPostPartInfoRequest, opts ...client.CallOption) (*ListPostPartInfoResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListUserCreatedPost", in)
	out := new(ListPostPartInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.UpdatePostInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) SetQualityPost(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.SetQualityPost", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetUnReadPostNum(ctx context.Context, in *Request, opts ...client.CallOption) (*UnReadPostNumResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.GetUnReadPostNum", in)
	out := new(UnReadPostNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) UpdateLastReadTime(ctx context.Context, in *UpdateLastReadRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.UpdateLastReadTime", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateSipScore(ctx context.Context, in *CreateSipScoreRequest, opts ...client.CallOption) (*CreateSipScoreResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateSipScore", in)
	out := new(CreateSipScoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) UpdateSipScoreInfo(ctx context.Context, in *UpdateSipScoreInfoRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.UpdateSipScoreInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateSipScoreEntry(ctx context.Context, in *CreateSipScoreEntryRequest, opts ...client.CallOption) (*CreateSipScoreEntryResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateSipScoreEntry", in)
	out := new(CreateSipScoreEntryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) UpdateSipScoreEntryInfo(ctx context.Context, in *UpdateSipScoreEntryInfoRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.UpdateSipScoreEntryInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetSipScore(ctx context.Context, in *Request, opts ...client.CallOption) (*SipScore, error) {
	req := c.c.NewRequest(c.name, "PostService.GetSipScore", in)
	out := new(SipScore)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListSipScoreEntry(ctx context.Context, in *ListSipScoreEntryRequest, opts ...client.CallOption) (*ListSipScoreEntryResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListSipScoreEntry", in)
	out := new(ListSipScoreEntryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) DeleteSipScoreEntries(ctx context.Context, in *DeleteSipScoreEntriesRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.DeleteSipScoreEntries", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListSipScore(ctx context.Context, in *ListSipScoreRequest, opts ...client.CallOption) (*ListSipScoreResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListSipScore", in)
	out := new(ListSipScoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateSipScoreEntryCommentRating(ctx context.Context, in *CreateSipScoreEntryCommentRatingRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateSipScoreEntryCommentRating", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) UpdateSipScoreEntryCommentRatingInfo(ctx context.Context, in *UpdateSipScoreEntryCommentRatingInfoRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.UpdateSipScoreEntryCommentRatingInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) DeleteSipScoreEntryCommentRating(ctx context.Context, in *DeleteSipScoreEntryCommentRatingRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.DeleteSipScoreEntryCommentRating", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListSipScoreEntryCommentRating(ctx context.Context, in *ListSipScoreEntryCommentRatingInfoRequest, opts ...client.CallOption) (*ListSipScoreEntryCommentRatingInfoResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListSipScoreEntryCommentRating", in)
	out := new(ListSipScoreEntryCommentRatingInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetComment(ctx context.Context, in *Request, opts ...client.CallOption) (*CommentInfo, error) {
	req := c.c.NewRequest(c.name, "PostService.GetComment", in)
	out := new(CommentInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*CreateCommentResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateComment", in)
	out := new(CreateCommentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreatePostComment(ctx context.Context, in *CreatePostCommentRequest, opts ...client.CallOption) (*CreatePostCommentResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreatePostComment", in)
	out := new(CreatePostCommentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.DeleteItem", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateOrRemoveLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateOrRemoveLike", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListLikeByUserId(ctx context.Context, in *ListPostPartInfoRequest, opts ...client.CallOption) (*ListPostPartInfoResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListLikeByUserId", in)
	out := new(ListPostPartInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListPopularTag(ctx context.Context, in *ListPopularTagRequest, opts ...client.CallOption) (*Tags, error) {
	req := c.c.NewRequest(c.name, "PostService.ListPopularTag", in)
	out := new(Tags)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateOrRemoveCollection(ctx context.Context, in *ToggleTargetRequest, opts ...client.CallOption) (*CreateOrRemoveCollectionResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateOrRemoveCollection", in)
	out := new(CreateOrRemoveCollectionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListCollection(ctx context.Context, in *ListPostPartInfoRequest, opts ...client.CallOption) (*ListPostPartInfoResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListCollection", in)
	out := new(ListPostPartInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.CreateReport", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) ListReport(ctx context.Context, in *ListReportRequest, opts ...client.CallOption) (*ListReportResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.ListReport", in)
	out := new(ListReportResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) HandleReport(ctx context.Context, in *HandleReportRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostService.HandleReport", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostService service

type PostServiceHandler interface {
	CreatePost(context.Context, *CreatePostRequest, *CreatePostResponse) error
	GetPost(context.Context, *Request, *Post) error
	ListMainPost(context.Context, *ListMainPostRequest, *ListPostResponse) error
	ListUserCreatedPost(context.Context, *ListPostPartInfoRequest, *ListPostPartInfoResponse) error
	UpdatePostInfo(context.Context, *UpdatePostInfoRequest, *Response) error
	SetQualityPost(context.Context, *Request, *Response) error
	GetUnReadPostNum(context.Context, *Request, *UnReadPostNumResponse) error
	UpdateLastReadTime(context.Context, *UpdateLastReadRequest, *Response) error
	CreateSipScore(context.Context, *CreateSipScoreRequest, *CreateSipScoreResponse) error
	UpdateSipScoreInfo(context.Context, *UpdateSipScoreInfoRequest, *Response) error
	CreateSipScoreEntry(context.Context, *CreateSipScoreEntryRequest, *CreateSipScoreEntryResponse) error
	UpdateSipScoreEntryInfo(context.Context, *UpdateSipScoreEntryInfoRequest, *Response) error
	GetSipScore(context.Context, *Request, *SipScore) error
	ListSipScoreEntry(context.Context, *ListSipScoreEntryRequest, *ListSipScoreEntryResponse) error
	DeleteSipScoreEntries(context.Context, *DeleteSipScoreEntriesRequest, *Response) error
	ListSipScore(context.Context, *ListSipScoreRequest, *ListSipScoreResponse) error
	CreateSipScoreEntryCommentRating(context.Context, *CreateSipScoreEntryCommentRatingRequest, *Response) error
	UpdateSipScoreEntryCommentRatingInfo(context.Context, *UpdateSipScoreEntryCommentRatingInfoRequest, *Response) error
	DeleteSipScoreEntryCommentRating(context.Context, *DeleteSipScoreEntryCommentRatingRequest, *Response) error
	ListSipScoreEntryCommentRating(context.Context, *ListSipScoreEntryCommentRatingInfoRequest, *ListSipScoreEntryCommentRatingInfoResponse) error
	GetComment(context.Context, *Request, *CommentInfo) error
	// 通用创建评论（target_type + target_id）
	CreateComment(context.Context, *CreateCommentRequest, *CreateCommentResponse) error
	CreatePostComment(context.Context, *CreatePostCommentRequest, *CreatePostCommentResponse) error
	DeleteItem(context.Context, *DeleteItemRequest, *Response) error
	CreateOrRemoveLike(context.Context, *LikeRequest, *Response) error
	ListLikeByUserId(context.Context, *ListPostPartInfoRequest, *ListPostPartInfoResponse) error
	ListPopularTag(context.Context, *ListPopularTagRequest, *Tags) error
	CreateOrRemoveCollection(context.Context, *ToggleTargetRequest, *CreateOrRemoveCollectionResponse) error
	ListCollection(context.Context, *ListPostPartInfoRequest, *ListPostPartInfoResponse) error
	CreateReport(context.Context, *CreateReportRequest, *Response) error
	ListReport(context.Context, *ListReportRequest, *ListReportResponse) error
	HandleReport(context.Context, *HandleReportRequest, *Response) error
}

func RegisterPostServiceHandler(s server.Server, hdlr PostServiceHandler, opts ...server.HandlerOption) error {
	type postService interface {
		CreatePost(ctx context.Context, in *CreatePostRequest, out *CreatePostResponse) error
		GetPost(ctx context.Context, in *Request, out *Post) error
		ListMainPost(ctx context.Context, in *ListMainPostRequest, out *ListPostResponse) error
		ListUserCreatedPost(ctx context.Context, in *ListPostPartInfoRequest, out *ListPostPartInfoResponse) error
		UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, out *Response) error
		SetQualityPost(ctx context.Context, in *Request, out *Response) error
		GetUnReadPostNum(ctx context.Context, in *Request, out *UnReadPostNumResponse) error
		UpdateLastReadTime(ctx context.Context, in *UpdateLastReadRequest, out *Response) error
		CreateSipScore(ctx context.Context, in *CreateSipScoreRequest, out *CreateSipScoreResponse) error
		UpdateSipScoreInfo(ctx context.Context, in *UpdateSipScoreInfoRequest, out *Response) error
		CreateSipScoreEntry(ctx context.Context, in *CreateSipScoreEntryRequest, out *CreateSipScoreEntryResponse) error
		UpdateSipScoreEntryInfo(ctx context.Context, in *UpdateSipScoreEntryInfoRequest, out *Response) error
		GetSipScore(ctx context.Context, in *Request, out *SipScore) error
		ListSipScoreEntry(ctx context.Context, in *ListSipScoreEntryRequest, out *ListSipScoreEntryResponse) error
		DeleteSipScoreEntries(ctx context.Context, in *DeleteSipScoreEntriesRequest, out *Response) error
		ListSipScore(ctx context.Context, in *ListSipScoreRequest, out *ListSipScoreResponse) error
		CreateSipScoreEntryCommentRating(ctx context.Context, in *CreateSipScoreEntryCommentRatingRequest, out *Response) error
		UpdateSipScoreEntryCommentRatingInfo(ctx context.Context, in *UpdateSipScoreEntryCommentRatingInfoRequest, out *Response) error
		DeleteSipScoreEntryCommentRating(ctx context.Context, in *DeleteSipScoreEntryCommentRatingRequest, out *Response) error
		ListSipScoreEntryCommentRating(ctx context.Context, in *ListSipScoreEntryCommentRatingInfoRequest, out *ListSipScoreEntryCommentRatingInfoResponse) error
		GetComment(ctx context.Context, in *Request, out *CommentInfo) error
		CreateComment(ctx context.Context, in *CreateCommentRequest, out *CreateCommentResponse) error
		CreatePostComment(ctx context.Context, in *CreatePostCommentRequest, out *CreatePostCommentResponse) error
		DeleteItem(ctx context.Context, in *DeleteItemRequest, out *Response) error
		CreateOrRemoveLike(ctx context.Context, in *LikeRequest, out *Response) error
		ListLikeByUserId(ctx context.Context, in *ListPostPartInfoRequest, out *ListPostPartInfoResponse) error
		ListPopularTag(ctx context.Context, in *ListPopularTagRequest, out *Tags) error
		CreateOrRemoveCollection(ctx context.Context, in *ToggleTargetRequest, out *CreateOrRemoveCollectionResponse) error
		ListCollection(ctx context.Context, in *ListPostPartInfoRequest, out *ListPostPartInfoResponse) error
		CreateReport(ctx context.Context, in *CreateReportRequest, out *Response) error
		ListReport(ctx context.Context, in *ListReportRequest, out *ListReportResponse) error
		HandleReport(ctx context.Context, in *HandleReportRequest, out *Response) error
	}
	type PostService struct {
		postService
	}
	h := &postServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PostService{h}, opts...))
}

type postServiceHandler struct {
	PostServiceHandler
}

func (h *postServiceHandler) CreatePost(ctx context.Context, in *CreatePostRequest, out *CreatePostResponse) error {
	return h.PostServiceHandler.CreatePost(ctx, in, out)
}

func (h *postServiceHandler) GetPost(ctx context.Context, in *Request, out *Post) error {
	return h.PostServiceHandler.GetPost(ctx, in, out)
}

func (h *postServiceHandler) ListMainPost(ctx context.Context, in *ListMainPostRequest, out *ListPostResponse) error {
	return h.PostServiceHandler.ListMainPost(ctx, in, out)
}

func (h *postServiceHandler) ListUserCreatedPost(ctx context.Context, in *ListPostPartInfoRequest, out *ListPostPartInfoResponse) error {
	return h.PostServiceHandler.ListUserCreatedPost(ctx, in, out)
}

func (h *postServiceHandler) UpdatePostInfo(ctx context.Context, in *UpdatePostInfoRequest, out *Response) error {
	return h.PostServiceHandler.UpdatePostInfo(ctx, in, out)
}

func (h *postServiceHandler) SetQualityPost(ctx context.Context, in *Request, out *Response) error {
	return h.PostServiceHandler.SetQualityPost(ctx, in, out)
}

func (h *postServiceHandler) GetUnReadPostNum(ctx context.Context, in *Request, out *UnReadPostNumResponse) error {
	return h.PostServiceHandler.GetUnReadPostNum(ctx, in, out)
}

func (h *postServiceHandler) UpdateLastReadTime(ctx context.Context, in *UpdateLastReadRequest, out *Response) error {
	return h.PostServiceHandler.UpdateLastReadTime(ctx, in, out)
}

func (h *postServiceHandler) CreateSipScore(ctx context.Context, in *CreateSipScoreRequest, out *CreateSipScoreResponse) error {
	return h.PostServiceHandler.CreateSipScore(ctx, in, out)
}

func (h *postServiceHandler) UpdateSipScoreInfo(ctx context.Context, in *UpdateSipScoreInfoRequest, out *Response) error {
	return h.PostServiceHandler.UpdateSipScoreInfo(ctx, in, out)
}

func (h *postServiceHandler) CreateSipScoreEntry(ctx context.Context, in *CreateSipScoreEntryRequest, out *CreateSipScoreEntryResponse) error {
	return h.PostServiceHandler.CreateSipScoreEntry(ctx, in, out)
}

func (h *postServiceHandler) UpdateSipScoreEntryInfo(ctx context.Context, in *UpdateSipScoreEntryInfoRequest, out *Response) error {
	return h.PostServiceHandler.UpdateSipScoreEntryInfo(ctx, in, out)
}

func (h *postServiceHandler) GetSipScore(ctx context.Context, in *Request, out *SipScore) error {
	return h.PostServiceHandler.GetSipScore(ctx, in, out)
}

func (h *postServiceHandler) ListSipScoreEntry(ctx context.Context, in *ListSipScoreEntryRequest, out *ListSipScoreEntryResponse) error {
	return h.PostServiceHandler.ListSipScoreEntry(ctx, in, out)
}

func (h *postServiceHandler) DeleteSipScoreEntries(ctx context.Context, in *DeleteSipScoreEntriesRequest, out *Response) error {
	return h.PostServiceHandler.DeleteSipScoreEntries(ctx, in, out)
}

func (h *postServiceHandler) ListSipScore(ctx context.Context, in *ListSipScoreRequest, out *ListSipScoreResponse) error {
	return h.PostServiceHandler.ListSipScore(ctx, in, out)
}

func (h *postServiceHandler) CreateSipScoreEntryCommentRating(ctx context.Context, in *CreateSipScoreEntryCommentRatingRequest, out *Response) error {
	return h.PostServiceHandler.CreateSipScoreEntryCommentRating(ctx, in, out)
}

func (h *postServiceHandler) UpdateSipScoreEntryCommentRatingInfo(ctx context.Context, in *UpdateSipScoreEntryCommentRatingInfoRequest, out *Response) error {
	return h.PostServiceHandler.UpdateSipScoreEntryCommentRatingInfo(ctx, in, out)
}

func (h *postServiceHandler) DeleteSipScoreEntryCommentRating(ctx context.Context, in *DeleteSipScoreEntryCommentRatingRequest, out *Response) error {
	return h.PostServiceHandler.DeleteSipScoreEntryCommentRating(ctx, in, out)
}

func (h *postServiceHandler) ListSipScoreEntryCommentRating(ctx context.Context, in *ListSipScoreEntryCommentRatingInfoRequest, out *ListSipScoreEntryCommentRatingInfoResponse) error {
	return h.PostServiceHandler.ListSipScoreEntryCommentRating(ctx, in, out)
}

func (h *postServiceHandler) GetComment(ctx context.Context, in *Request, out *CommentInfo) error {
	return h.PostServiceHandler.GetComment(ctx, in, out)
}

func (h *postServiceHandler) CreateComment(ctx context.Context, in *CreateCommentRequest, out *CreateCommentResponse) error {
	return h.PostServiceHandler.CreateComment(ctx, in, out)
}

func (h *postServiceHandler) CreatePostComment(ctx context.Context, in *CreatePostCommentRequest, out *CreatePostCommentResponse) error {
	return h.PostServiceHandler.CreatePostComment(ctx, in, out)
}

func (h *postServiceHandler) DeleteItem(ctx context.Context, in *DeleteItemRequest, out *Response) error {
	return h.PostServiceHandler.DeleteItem(ctx, in, out)
}

func (h *postServiceHandler) CreateOrRemoveLike(ctx context.Context, in *LikeRequest, out *Response) error {
	return h.PostServiceHandler.CreateOrRemoveLike(ctx, in, out)
}

func (h *postServiceHandler) ListLikeByUserId(ctx context.Context, in *ListPostPartInfoRequest, out *ListPostPartInfoResponse) error {
	return h.PostServiceHandler.ListLikeByUserId(ctx, in, out)
}

func (h *postServiceHandler) ListPopularTag(ctx context.Context, in *ListPopularTagRequest, out *Tags) error {
	return h.PostServiceHandler.ListPopularTag(ctx, in, out)
}

func (h *postServiceHandler) CreateOrRemoveCollection(ctx context.Context, in *ToggleTargetRequest, out *CreateOrRemoveCollectionResponse) error {
	return h.PostServiceHandler.CreateOrRemoveCollection(ctx, in, out)
}

func (h *postServiceHandler) ListCollection(ctx context.Context, in *ListPostPartInfoRequest, out *ListPostPartInfoResponse) error {
	return h.PostServiceHandler.ListCollection(ctx, in, out)
}

func (h *postServiceHandler) CreateReport(ctx context.Context, in *CreateReportRequest, out *Response) error {
	return h.PostServiceHandler.CreateReport(ctx, in, out)
}

func (h *postServiceHandler) ListReport(ctx context.Context, in *ListReportRequest, out *ListReportResponse) error {
	return h.PostServiceHandler.ListReport(ctx, in, out)
}

func (h *postServiceHandler) HandleReport(ctx context.Context, in *HandleReportRequest, out *Response) error {
	return h.PostServiceHandler.HandleReport(ctx, in, out)
}
