// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/feed.proto

package feed

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PushRequest struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Source               *Source  `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{1}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *PushRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PushRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type ListRequest struct {
	LastId uint32 `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Role   uint32 `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	//    uint32 user_id = 5;
	UserId               uint32   `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              uint32   `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Pagination           bool     `protobuf:"varint,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLastId() uint32 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *ListRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *ListRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *ListRequest) GetPagination() bool {
	if m != nil {
		return m.Pagination
	}
	return false
}

type ListResponse struct {
	List                 []*FeedItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetList() []*FeedItem {
	if m != nil {
		return m.List
	}
	return nil
}

type FeedItem struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ShowDivider          bool     `protobuf:"varint,3,opt,name=show_divider,json=showDivider,proto3" json:"show_divider,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	User                 *User    `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Source               *Source  `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedItem) Reset()         { *m = FeedItem{} }
func (m *FeedItem) String() string { return proto.CompactTextString(m) }
func (*FeedItem) ProtoMessage()    {}
func (*FeedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{5}
}

func (m *FeedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItem.Unmarshal(m, b)
}
func (m *FeedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItem.Marshal(b, m, deterministic)
}
func (m *FeedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItem.Merge(m, src)
}
func (m *FeedItem) XXX_Size() int {
	return xxx_messageInfo_FeedItem.Size(m)
}
func (m *FeedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItem.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItem proto.InternalMessageInfo

func (m *FeedItem) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeedItem) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *FeedItem) GetShowDivider() bool {
	if m != nil {
		return m.ShowDivider
	}
	return false
}

func (m *FeedItem) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *FeedItem) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *FeedItem) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

// source: feed的来源.
type Source struct {
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TypeName             string   `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e1d1466bbab432, []int{7}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Source) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "feed.Request")
	proto.RegisterType((*PushRequest)(nil), "feed.PushRequest")
	proto.RegisterType((*Response)(nil), "feed.Response")
	proto.RegisterType((*ListRequest)(nil), "feed.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "feed.ListResponse")
	proto.RegisterType((*FeedItem)(nil), "feed.FeedItem")
	proto.RegisterType((*User)(nil), "feed.User")
	proto.RegisterType((*Source)(nil), "feed.Source")
}

func init() { proto.RegisterFile("proto/feed.proto", fileDescriptor_96e1d1466bbab432) }

var fileDescriptor_96e1d1466bbab432 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xff, 0x6a, 0xd4, 0x40,
	0x10, 0x36, 0x69, 0x9a, 0x1f, 0x93, 0xbb, 0xa2, 0x8b, 0xd8, 0xb4, 0x62, 0x3d, 0x83, 0x7f, 0x9c,
	0x08, 0x2d, 0xc4, 0x57, 0x28, 0x42, 0x40, 0x44, 0xb6, 0xf6, 0xef, 0x10, 0x6f, 0xe7, 0xda, 0x85,
	0xe4, 0x12, 0x77, 0x37, 0x27, 0xbe, 0x88, 0x4f, 0xe3, 0xc3, 0xc9, 0xce, 0x26, 0x67, 0xaa, 0xe8,
	0x7f, 0x33, 0xdf, 0x64, 0xbf, 0xf9, 0xbe, 0x99, 0x09, 0x3c, 0xee, 0x55, 0x67, 0xba, 0xab, 0x2d,
	0xa2, 0xb8, 0xa4, 0x90, 0x05, 0x36, 0xce, 0xcf, 0x20, 0xe2, 0xf8, 0x75, 0x40, 0x6d, 0xd8, 0x09,
	0xf8, 0x52, 0x64, 0xde, 0xca, 0x5b, 0x2f, 0xb9, 0x2f, 0x45, 0x2e, 0x20, 0xfd, 0x34, 0xe8, 0xfb,
	0xa9, 0xfc, 0x0c, 0xc2, 0x7a, 0x63, 0x64, 0xb7, 0xa3, 0x4f, 0x12, 0x3e, 0x66, 0xec, 0x14, 0xa2,
	0x41, 0xa3, 0xaa, 0xa4, 0xc8, 0x7c, 0x7a, 0x1b, 0xda, 0xb4, 0x14, 0xec, 0x35, 0x84, 0xba, 0x1b,
	0xd4, 0x06, 0xb3, 0xa3, 0x95, 0xb7, 0x4e, 0x8b, 0xc5, 0x25, 0x75, 0xbf, 0x21, 0x8c, 0x8f, 0xb5,
	0x1c, 0x20, 0xe6, 0xa8, 0xfb, 0x6e, 0xa7, 0x31, 0xff, 0xe9, 0x41, 0xfa, 0x41, 0x6a, 0x33, 0xb5,
	0x3c, 0x85, 0xa8, 0xa9, 0xb5, 0xa9, 0x0e, 0xb2, 0x42, 0x9b, 0x96, 0x82, 0x3d, 0x85, 0xe3, 0x46,
	0xb6, 0xd2, 0x8c, 0x1d, 0x5d, 0x62, 0x15, 0x76, 0xdb, 0xad, 0x46, 0x43, 0x0d, 0x97, 0x7c, 0xcc,
	0x18, 0x83, 0x40, 0x75, 0x0d, 0x66, 0x01, 0xa1, 0x14, 0xcf, 0x55, 0x1f, 0x3f, 0x50, 0x7d, 0x06,
	0xf1, 0x9d, 0xea, 0x86, 0xde, 0x56, 0x42, 0xaa, 0x44, 0x94, 0x97, 0x82, 0x5d, 0x00, 0xf4, 0xf5,
	0x9d, 0xdc, 0xd5, 0x34, 0x85, 0x68, 0xe5, 0xad, 0x63, 0x3e, 0x43, 0xf2, 0x02, 0x16, 0x4e, 0xbd,
	0xb3, 0xc3, 0x72, 0x08, 0x1a, 0xa9, 0x4d, 0xe6, 0xad, 0x8e, 0xd6, 0x69, 0x71, 0xe2, 0xec, 0xbf,
	0x47, 0x14, 0xa5, 0xc1, 0x96, 0x53, 0xcd, 0x5a, 0x8e, 0x27, 0xe8, 0xcf, 0x0d, 0xcc, 0x46, 0xee,
	0x3f, 0x18, 0xf9, 0x2b, 0x58, 0xe8, 0xfb, 0xee, 0x5b, 0x25, 0xe4, 0x5e, 0x0a, 0x54, 0x64, 0x37,
	0xe6, 0xa9, 0xc5, 0xae, 0x1d, 0xc4, 0x5e, 0x42, 0xba, 0x51, 0x58, 0x1b, 0xac, 0x8c, 0x6c, 0x9d,
	0xf5, 0x84, 0x83, 0x83, 0x3e, 0xcb, 0x16, 0xd9, 0x05, 0x04, 0xd6, 0x31, 0xb9, 0x4f, 0x0b, 0x70,
	0xe2, 0x6e, 0x35, 0x2a, 0x4e, 0xf8, 0x6c, 0x7b, 0xe1, 0x7f, 0xb6, 0x57, 0x42, 0x60, 0xdf, 0xfc,
	0xa5, 0x9c, 0x41, 0xb0, 0xab, 0x5b, 0x1c, 0x75, 0x53, 0xcc, 0x5e, 0x00, 0xd4, 0xfb, 0xda, 0xd4,
	0xaa, 0x1a, 0x54, 0x43, 0x9a, 0x13, 0x9e, 0x38, 0xe4, 0x56, 0x35, 0x79, 0x09, 0xa1, 0x23, 0x1f,
	0xc9, 0xfc, 0x03, 0xd9, 0x73, 0x48, 0xcc, 0xf7, 0x1e, 0x2b, 0x62, 0x74, 0xc7, 0x17, 0x5b, 0xe0,
	0xa3, 0x65, 0x9d, 0x3a, 0x1d, 0xfd, 0xee, 0x54, 0xfc, 0xf0, 0x20, 0xb5, 0x43, 0xbd, 0x41, 0xb5,
	0x97, 0x1b, 0x64, 0x6f, 0x21, 0xb0, 0x97, 0xcc, 0x9e, 0x38, 0x0f, 0xb3, 0xab, 0x3e, 0x1f, 0xb7,
	0x72, 0x38, 0xc1, 0x47, 0xec, 0x0a, 0x02, 0xbb, 0xc5, 0xe9, 0xe3, 0xd9, 0x3d, 0x9e, 0xb3, 0x39,
	0x74, 0x78, 0xf0, 0x06, 0xc2, 0x6b, 0x6c, 0xd0, 0x20, 0x5b, 0x4e, 0x64, 0xff, 0xe0, 0xfe, 0x12,
	0xd2, 0xaf, 0xf7, 0xee, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0x19, 0x6f, 0xe1, 0x8e, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FeedService service

type FeedServiceClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...client.CallOption) (*Response, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type feedServiceClient struct {
	c           client.Client
	serviceName string
}

func NewFeedServiceClient(serviceName string, c client.Client) FeedServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "feed"
	}
	return &feedServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *feedServiceClient) Push(ctx context.Context, in *PushRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FeedService.Push", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "FeedService.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FeedService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedService service

type FeedServiceHandler interface {
	Push(context.Context, *PushRequest, *Response) error
	List(context.Context, *ListRequest, *ListResponse) error
	Delete(context.Context, *Request, *Response) error
}

func RegisterFeedServiceHandler(s server.Server, hdlr FeedServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&FeedService{hdlr}, opts...))
}

type FeedService struct {
	FeedServiceHandler
}

func (h *FeedService) Push(ctx context.Context, in *PushRequest, out *Response) error {
	return h.FeedServiceHandler.Push(ctx, in, out)
}

func (h *FeedService) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.FeedServiceHandler.List(ctx, in, out)
}

func (h *FeedService) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.FeedServiceHandler.Delete(ctx, in, out)
}
